
import React from 'react';
import { 
  Brain, Layout, Server, Database, Cloud, Code, 
  Trophy, Award, GraduationCap, Star, Zap, Globe, 
  Cpu, Terminal, Layers, Wrench, Shield, Smartphone,
  FolderGit2, Rocket, Lightbulb, Target, Users, Briefcase,
  GitBranch, Container, Braces, Command, Monitor, Tablet,
  Bot, Sparkles, TrendingUp, CheckCircle, Crown, Medal,
  Flag, MapPin, Calendar, Clock, FileCode, Settings,
  Search, PenTool, Palette, Box, Link, Hash, FileJson,
  Activity, Anchor, Aperture, Archive, ArrowRight,
  Book, Bookmark, Camera, Circle, Clipboard, Compass,
  CreditCard, DollarSign, Download, Eye, Feather,
  FileText, Folder, Grid, HardDrive, Heart, Home,
  Image, Inbox, Key, Laptop, LifeBuoy, List,
  Lock, Mail, Map, Menu, MessageSquare, Mic,
  Moon, MousePointer, Music, Package, Paperclip,
  Percent, PieChart, Play, Power, Printer, Radio,
  RefreshCw, Repeat, Save, Scissors, Share, ShoppingBag,
  ShoppingCart, Sidebar, Sliders, Speaker, Square,
  Sun, Table, Tag, Thermometer, ThumbsUp, ToggleLeft,
  ToggleRight, Trash, Truck, Tv, Umbrella,
  Upload, User, UserCheck, UserPlus, UserMinus,
  Video, Voicemail, Volume, Volume1, Volume2,
  Watch, Wifi, Wind, X, BarChart3
} from 'lucide-react';

// Map PocketBase text values to Lucide Components
export const IconMap: Record<string, React.FC<any>> = {
  // --- Tech & Dev ---
  'brain': Brain,
  'layout': Layout,
  'server': Server,
  'database': Database,
  'cloud': Cloud,
  'code': Code,
  'cpu': Cpu,
  'terminal': Terminal,
  'layers': Layers,
  'git-branch': GitBranch,
  'container': Container,
  'braces': Braces,
  'command': Command,
  'bot': Bot,
  'file-code': FileCode,
  'file-json': FileJson,
  'hash': Hash,
  'hard-drive': HardDrive,
  'laptop': Laptop,
  'monitor': Monitor,
  'desktop': Monitor, // Alias
  'smartphone': Smartphone,
  'mobile': Smartphone, // Alias
  'tablet': Tablet,
  'folder-git-2': FolderGit2,
  'wifi': Wifi,

  // --- Achievements & Stats ---
  'trophy': Trophy,
  'award': Award,
  'medal': Medal,
  'crown': Crown,
  'star': Star,
  'target': Target,
  'trending-up': TrendingUp,
  'flag': Flag,
  'zap': Zap,
  'activity': Activity,
  'percent': Percent,
  'pie-chart': PieChart,
  'bar-chart': BarChart3,
  'bar-chart-3': BarChart3,
  'thumbs-up': ThumbsUp,
  'check-circle': CheckCircle,
  'graduation-cap': GraduationCap,

  // --- Design & Creative ---
  'pen-tool': PenTool,
  'palette': Palette,
  'image': Image,
  'camera': Camera,
  'video': Video,
  'music': Music,
  'feather': Feather,
  'grid': Grid,
  'scissors': Scissors,
  'sparkles': Sparkles,
  'aperture': Aperture,

  // --- Business & General ---
  'rocket': Rocket,
  'lightbulb': Lightbulb,
  'briefcase': Briefcase,
  'users': Users,
  'user': User,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'globe': Globe,
  'map-pin': MapPin,
  'map': Map,
  'calendar': Calendar,
  'clock': Clock,
  'mail': Mail,
  'inbox': Inbox,
  'message-square': MessageSquare,
  'phone': Smartphone,
  'link': Link,
  'search': Search,
  'settings': Settings,
  'sliders': Sliders,
  'tool': Wrench,
  'wrench': Wrench,
  'shield': Shield,
  'lock': Lock,
  'key': Key,
  'home': Home,
  'box': Box,
  'package': Package,
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  'file-text': FileText,
  'book': Book,
  'bookmark': Bookmark,
  'paperclip': Paperclip,
  'tag': Tag,
  'list': List,
  'filter': Sliders,
  
  // --- UI / Navigation / Actions ---
  'anchor': Anchor,
  'archive': Archive,
  'arrow-right': ArrowRight,
  'circle': Circle,
  'clipboard': Clipboard,
  'compass': Compass,
  'download': Download,
  'eye': Eye,
  'folder': Folder,
  'heart': Heart,
  'life-buoy': LifeBuoy,
  'menu': Menu,
  'mic': Mic,
  'moon': Moon,
  'sun': Sun,
  'mouse-pointer': MousePointer,
  'play': Play,
  'power': Power,
  'printer': Printer,
  'radio': Radio,
  'refresh-cw': RefreshCw,
  'repeat': Repeat,
  'save': Save,
  'share': Share,
  'sidebar': Sidebar,
  'speaker': Speaker,
  'square': Square,
  'table': Table,
  'thermometer': Thermometer,
  'toggle-left': ToggleLeft,
  'toggle-right': ToggleRight,
  'trash': Trash,
  'truck': Truck,
  'tv': Tv,
  'umbrella': Umbrella,
  'upload': Upload,
  'voicemail': Voicemail,
  'volume': Volume,
  'volume-1': Volume1,
  'volume-2': Volume2,
  'watch': Watch,
  'wind': Wind,
  'x': X,
};

export const getIcon = (name: string, props: any = {}) => {
  const normalized = name.toLowerCase().replace(/\s+/g, '-');
  const IconComponent = IconMap[normalized] || Code; // Default to Code if not found
  return <IconComponent {...props} />;
};
